quarkus.http.port=8082

mp.messaging.incoming.messages-in.connector=smallrye-kafka
mp.messaging.incoming.messages-in.topic=test-topic
mp.messaging.incoming.messages-in.key.deserializer=org.apache.kafka.common.serialization.StringDeserializer
mp.messaging.incoming.messages-in.value.deserializer=org.apache.kafka.common.serialization.StringDeserializer
mp.messaging.incoming.messages-in.group.id=consumer-api-group
mp.messaging.incoming.messages-in.auto.offset.reset=earliest

kafka.bootstrap.servers=localhost:9092
# Definir nivel de log
quarkus.log.category."ar.gob.ushuaia".level=DEBUG