quarkus.http.port=8082

# Canal de entrada "messages-in" (consumido con @Incoming en MessageConsumer) usando el conector Kafka de SmallRye
mp.messaging.incoming.messages-in.connector=smallrye-kafka
# Topic Kafka desde el que se consumen los mensajes
mp.messaging.incoming.messages-in.topic=test-topic
# Deserializador de la key del mensaje (String)
mp.messaging.incoming.messages-in.key.deserializer=org.apache.kafka.common.serialization.StringDeserializer
# Deserializador del value del mensaje (String)
mp.messaging.incoming.messages-in.value.deserializer=org.apache.kafka.common.serialization.StringDeserializer
# Grupo de consumidores Kafka al que pertenece esta instancia
mp.messaging.incoming.messages-in.group.id=consumer-api-group
# Si no hay offset previo, empieza a leer desde el mensaje más antiguo del topic
mp.messaging.incoming.messages-in.auto.offset.reset=earliest

# Dirección del broker Kafka al que se conecta el consumer
kafka.bootstrap.servers=localhost:9092
# Definir nivel de log
quarkus.log.category."ar.gob.ushuaia".level=DEBUG