quarkus.http.port=8081

# Canal de salida "messages-out" (inyectado como Emitter en MessageResource) usando el conector Kafka de SmallRye
mp.messaging.outgoing.messages-out.connector=smallrye-kafka
# Topic Kafka al que se publican los mensajes
mp.messaging.outgoing.messages-out.topic=test-topic
# Serializador de la key del mensaje (String)
mp.messaging.outgoing.messages-out.key.serializer=org.apache.kafka.common.serialization.StringSerializer
# Serializador del value del mensaje (String)
mp.messaging.outgoing.messages-out.value.serializer=org.apache.kafka.common.serialization.StringSerializer

# Dirección del broker Kafka al que se conecta el producer
kafka.bootstrap.servers=localhost:9092

# Definir nivel de log
quarkus.log.category."ar.gob.ushuaia".level=DEBUG